<?php
$this->headTitle('New Post');

$this->mainMenu()->setActiveItemId('posts');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('admin'),
            'Add Post'=>$this->url('admin', ['action'=>'add'])
            ]);

$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter post title here'
    ]);
$form->get('original_title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter original title here'
]);
$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Description',
    'rows'=>6
]);
$form->get('short_description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Short Description',
    'rows'=>3
]);
$form->get('video_src')->setAttributes([
    'class'=>'form-control'
]);
$form->get('cuisine_country')->setAttributes([
    'class'=>'form-control'
]);
$form->get('cuisine_type')->setAttributes([
    'class'=>'form-control'
]);
$form->get('recommended_restaurant')->setAttributes([
    'class'=>'form-control'
]);
$form->get('restaurant_street')->setAttributes([
    'class'=>'form-control'
]);
$form->get('city')->setAttributes([
    'class'=>'form-control'
]);
$form->get('image')->setAttributes([
    'class'=>'form-control'
]);
$form->get('tags')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'comma, separated, list, of, tags'
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control'   
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Add New Post</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('original_title')); ?>
            <?= $this->formElement($form->get('original_title')); ?>
            <?= $this->formElementErrors($form->get('original_title')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('short_description')); ?>
            <?= $this->formElement($form->get('short_description')); ?>
            <?= $this->formElementErrors($form->get('short_description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('video_src')); ?>
            <?= $this->formElement($form->get('video_src')); ?>
            <?= $this->formElementErrors($form->get('video_src')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('cuisine_country')); ?>
            <?= $this->formElement($form->get('cuisine_country')); ?>
            <?= $this->formElementErrors($form->get('cuisine_country')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('cuisine_type')); ?>
            <?= $this->formElement($form->get('cuisine_type')); ?>
            <?= $this->formElementErrors($form->get('cuisine_type')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('recommended_restaurant')); ?>
            <?= $this->formElement($form->get('recommended_restaurant')); ?>
            <?= $this->formElementErrors($form->get('recommended_restaurant')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('restaurant_street')); ?>
            <?= $this->formElement($form->get('restaurant_street')); ?>
            <?= $this->formElementErrors($form->get('restaurant_street')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('city')); ?>
            <?= $this->formElement($form->get('city')); ?>
            <?= $this->formElementErrors($form->get('city')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('image')); ?>
            <?= $this->formElement($form->get('image')); ?>
            <?= $this->formElementErrors($form->get('image')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('tags')); ?>
            <?= $this->formElement($form->get('tags')); ?>
            <?= $this->formElementErrors($form->get('tags')); ?>                  
            <p class="help-block">Separate tags with comma.</p>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   