<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Administrator Area')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.js'))
    ?>
</head>
<body>
<div class="container">
    <div class="row">
        <!-- Page header -->
        <div class="col-md-4">
            <div class="app-caption">Admin Area</div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- Navigation bar -->
            <?php
            // Initialize navbar items
            $this->mainMenu()->setItems([
                [
                    'id' => 'posts',
                    'label' => 'Posts',
                    'link' => $this->url('admin', ['action' => 'index'])
                ],
                [
                    'id' => 'users',
                    'label' => 'Users',
                    'link' => $this->url('users')
                ],
                [
                    'id' => 'logout',
                    'label' => 'Log Out',
                    'link' => '/logout'
                ],
            ]);

            // Check if the activeMenuItemId passed to layout view model
            // and if so, use it for setting active navbar item.
            if (isset($activeMenuItemId)) {
                $this->mainMenu()->setActiveItemId($activeMenuItemId);
            }

            // Render the navbar
            echo $this->mainMenu()->render();
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- Breadcrumbs -->
            <?= $this->pageBreadcrumbs()->render(); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- Page content placeholder -->
            <?= $this->content; ?>
        </div>
    </div>
    <hr>
    <footer>
        <p>Licenta ©2017 Soproncu Cristina</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
