<?php if ($this->pageCount > 1): ?>
    <div class="nav-links">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a class="previous page-numbers"
               href="<?php echo $this->url($this->route, [], ['query' => ['page' => $this->previous]]); ?>"><
                Previous</a>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a class="page-numbers"
                   href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]); ?>"><?= $this->escapeHtml($page); ?></a>
            <?php else: ?>
                <span class="page-numbers current"><?= $this->escapeHtml($page); ?></span>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a class="next page-numbers"
               href="<?php echo $this->url($this->route, [], ['query' => ['page' => $this->next]]); ?>">Next &gt;</a>
        <?php endif; ?>
    </div>
<?php endif; ?>