<div class="col-right col-pull">
    <div class="k-sidebar" data-get-height="content-2" data-break="767">

        <div id="pi_about-2" class="widget widget_about">
            <div class="img">
                <img src="/img/sidebar_banner.jpg" alt="The Blooming Trip">
            </div>
            <h5>Cuisine Tourism</h5>
            <div class="social">
                <a href="https://www.facebook.com/sharer.php?u=<?= $this->serverUrl(true); ?>&amp;t=Cuisine Tourism"
                   target="_blank" title="Share to Facebook">
                    <i class="fa fa-facebook" title="Facebook"></i>
                </a>
                <a href="https://twitter.com/intent/tweet?text=Cuisine Tourism-<?= $this->serverUrl(true); ?>&amp;source=webclient"
                   target="_blank" title="Share to Twitter">
                    <i class="fa fa-twitter" title="Twitter"></i>
                </a>
                <a href="https://pinterest.com/pin/create/button/?url=<?= $this->serverUrl(true); ?>&amp;media=<?= $this->serverUrl(false); ?>/img/sidebar_banner.jpg&amp;description=Cuisine Tourism"
                   target="_blank" data-pin-do="buttonBookmark" title="Share to Pinterest">
                    <i class="fa fa-pinterest" title="Pinterest "></i>
                </a>
                <a href="/about" data-toggle="tooltip" data-placement="top" title="About..." class="more">
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>
        </div>

        <div id="countries" class="widget widget_categories">
            <h4 class="widget-title">Cuisine Type</h4>
            <ul>
                <?php foreach ($this->types as $types): ?>
                    <li class="cat-item">
                        <a href="/recipes/type/<?= $types['cuisineType']; ?>">
                            <?= $this->escapeHtml($types['cuisineType']); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <div id="pi_postslisting-2" class="widget postslisting">
            <h4 class="widget-title">Latest Posts</h4>
            <ul class="widget_random_post">
                <?php foreach ($this->latestPosts as $post): ?>
                    <li>
                        <a href="/recipe/<?= $post->getId(); ?>" class="img">
                            <img width="120" height="80" src="<?= $post->getImage(); ?>"
                                 class="wp-post-image" alt="<?= $post->getTitle(); ?>">
                        </a>
                        <div class="caption">
                            <h4>
                                <a href="/recipe/<?= $post->getId(); ?>" data-toggle="tooltip"
                                   title="<?= $post->getTitle(); ?>"><?= $post->getTitle(); ?><span><i></i></span>
                                </a>
                            </h4>
                            <div class="post-meta">
                                <span>
                                    <i class="icon-basic-clock"></i><?= date('d-F-Y', strtotime($post->getDateCreated())); ?>
                                </span>
                                <span class="post-views">
                                    <i class="icon-basic-eye"></i> <?= $post->getViews(); ?>
                                </span>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <div id="types" class="widget widget_categories">
            <h4 class="widget-title">Country</h4>
            <ul>
                <?php foreach ($this->countries as $country): ?>
                    <li class="cat-item">
                        <a href="/recipes/country/<?= $country['cuisineCountry']; ?>">
                            <?= $this->escapeHtml($country['cuisineCountry']); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

    </div>
</div>
