<?php
$this->headTitle('Posts');
?>
    <div class="col-left col-push">
        <div class="k-content" data-set-height="content-2">
            <div class="blog-grid grid" data-col-lg="3" data-col-md="2" data-col-sm="2" data-col-xs="1"
                 data-horizontal="20" data-vertical="20">
                <div class="grid-size"></div>
                <?php foreach ($posts as $post): ?>

                    <div class="grid-item">
                        <div class="post type-post status-publish format-standard has-post-thumbnail hentry category-food tag-discover tag-explore tag-quotes tag-travel">
                            <div class="post-media">
                                <div class="img" data-set-height="post-176">
                                    <?php if ($post->getVideoSrc() !== NULL) { ?>
                                        <a href="https://www.youtube.com/watch?v=<?= $post->getVideoSrc(); ?>" class="pi-magnific-iframe icon-format">
                                            <i class="icon-music-play-button"></i>
                                        </a>
                                    <?php } ?>
                                    <a href="/recipe/<?= $post->getId(); ?>">
                                        <img width="525" height="350" src="<?= $post->getImage(); ?>"
                                             class="attachment-525x515 size-525x515 wp-post-image" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="post-body">
                                <div class="post-header">
                                    <h2 class="post-title">
                                        <a href="/recipe/<?= $post->getId(); ?>">
                                            <?= $this->escapeHtml($post->getTitle()); ?>
                                        </a>
                                    </h2>
                                    <div class="post-meta">
                                        <span class="post-comments">
                                            <i class="icon-basic-message-multiple"></i> <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?>
                                        </span>
                                        <span class="post-views">
                                            <i class="icon-basic-eye"></i> 2 Views
                                        </span>
                                        <span class="more-excerpt" data-toggle="tooltip" title="Excerpt More">
                                            <i class="fa fa-angle-down"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="group-box">
                                    <div class="post-content">
                                        <p><?= $this->escapeHtml($post->getShortDescription()); ?></p>
                                        <a href="/recipe/<?= $post->getId(); ?>"
                                           class="more">Continue reading</a>
                                    </div>
                                    <div class="post-footer">
                                        <hr class="hr">
                                        <div class="post-meta">
                                           <span>
                                                <i class="icon-basic-geolocalize-01"></i>
                                                Type: <?= $post->getCuisineType(); ?>
                                            </span>
                                            <span>
                                                <i class="icon-basic-geolocalize-01"></i>
                                                Country: <?= $post->getCuisineCountry(); ?>
                                            </span>
                                            <span>
                                                <i class="icon-basic-geolocalize-01"></i>
                                                Location: <?= $post->getCity(); ?>, <?= $post->getRecommendedRestaurant(); ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <nav class="navigation pagination" role="navigation">
                <?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator',
                    array('route' => 'application')); ?>
            </nav>

        </div>
    </div>
<?php echo $this->partial('application/partial/sidebar', ['tagCloud' => $this->tagCloud]); ?>